### ISSUE TITLE
Implement a dashboard for testing visualization 

### ISSUE THREAD

**Issue by Quentin-M** [coreos/tectonic-installer#1099]
In order to improve our ability to track test failures, increase our efficiency when finding the root cause/startin point of breakages, as well as enabling external users get a grasp of the current state of things, we should think about implementing a dashboard.

This dashboard should at least include a timeline view of every implemented test with green/red cells.

Gopi suggested https://github.com/capitalone/Hygieia during our last meeting. We should also look at what does upstream have.

/cc @gopilal @squat @robszumski

**Comment by Quentin-M** [comment]
There's also https://wiki.jenkins-ci.org/display/JENKINS/Build+Monitor+Plugin.

**Comment by squat** [comment]
Sounds like this will be faster to implement since we are already on jenkins. can we give this a shot before investing in hygieia?

**Comment by Quentin-M** [comment]
Yeah. Let's have @derekparker and @aaronlevy part in the loop for convergence on the solution.

**Comment by aaronlevy** [comment]
Another option to put out there is just using the upstream k8s test-grid project: https://github.com/kubernetes/test-infra/tree/master/testgrid

@ethernetdan has some experience setting that up

**Comment by philips** [comment]
+1 to using the upstream dashboard! I really think that is the best option and the upstream project could use signal on the platforms we are testing like vmware, openstack, etc.

**Comment by aaronlevy** [comment]
The downside is that the server side aspect of testgrid is not actually open source. We wouldn't be able to run our own, so we have to link our tests into an external test-grid instance. Due to that I might advocate for something relatively simple based on jenkins plugin to get started, and once our tests are in a place where we can publicly share log output & federating them makes more sense, maybe revisit adding to an external testgrid.
