### ISSUE TITLE
Support vanilla k8s upgrades

### ISSUE THREAD

**Issue by discordianfish** [coreos/tectonic-installer#1138]
Hi,

the tectonic-installer now also supports installation of vanilla k8s cluster. It should also provide *some* way to upgrade it without tectonic subscription.

The self-hosted components can be updated via the kubernetes api but the kubelet can't. As I understand it, in tectonic the UI installer upgrades the kubelet with help of the 'Kubernetes Version Operator' which isn't open source. I think this should also provide some 'official' way to update the kubelet. That could happen with `terraform apply` with appropriate limits but of course an automated way would be preferable. Maybe just open source the operator? :)

**Comment by robszumski** [comment]
Users can update `/etc/kubernetes/kubelet.env` directly or by writing that out by modifying the ignition profile.

The main problem is keeping the node in sync with changes going forward, which is where you get the benefit of Tectonic. This is where we are focusing most of our effort and due to team bandwidth I don't think we'll pursue anything more fancy for now.

**Comment by s-urbaniak** [comment]
closing for now for hygiene, please reopen if needed.

**Comment by discordianfish** [comment]
Yes, that's fair enough. Would be nice though to keep changes to `/etc/kubernetes/kubelet.env` minimal, so it can be used as somewhat stable integration point for custom upgrade scripts etc.
