### ISSUE TITLE
After a successful apply, the plan should be empty (idempotency)

### ISSUE THREAD

**Issue by Quentin-M** [coreos/tectonic-installer#1167]
Several times over the past months, we've seen issues where our code base was making Terraform apply/plan not idempotent. As these issues were discovered, we have always worked to fix them as soon as possible.

Recently, it was discovered that etcd nodes were being destroyed/re-created after a succesful apply [[1](https://github.com/coreos/tectonic-installer/issues/1035)]. This is a behavior I have warned us about during our first week of development in Berlin: etcd nodes being straight up EC2 instances, that can be renewed at any given time.

For some cases, `lifecycle { ignore_changes = [ ... ] }` can be used to mitigate. Sometimes, it has to be handled in other ways (i.e. `template_dir`).

In order to detect these problems early on, this issue proposes to add a check in our smoke tests that will ensure that `plan` will be a no-op after a successful apply.

cc @alexsomesan @s-urbaniak

**Comment by mxinden** [comment]
Current status: As pointed out by @s-urbaniak in person, current `master` does not have idempotent `apply` on AWS.

I am happy to add idempotency checks to our test pipeline, but I would like to wait for master to have idempotent applies, otherwise our test pipeline would be constantly failing.

@sym3tri Can we move this issue to the next sprint? @s-urbaniak and @alexsomesan can one of you help me make `master` applies idempotent?

**Comment by s-urbaniak** [comment]
xref #1446
