### ISSUE TITLE
Terraform apply fails while scaling up nodes count.

### ISSUE THREAD

**Issue by gopilal** [coreos/tectonic-installer#1297]
## Versions
* Tectonic version ([release](https://github.com/coreos/tectonic-installer/releases) or commit hash): 1.6.6
* Terraform version (`terraform version`): 
* Platform (aws|azure|openstack|metal): aws 

## What happened?
Terraform apply fails after scaling up the masters,workers & etcd count. 

## What you expected to happen?
Terraform apply should be successful and honor the increase in masters,workers & etcd count.

## How to reproduce it (as minimally and precisely as possible)?
- Launch the tectonic installer and update to 1 as the count for masters, workers & etcd count on the Nodes page. 
- Submit the installer with other default values. Download the assets upon successfull terraform apply and console launch.
- Follow the [instructions](https://coreos.com/tectonic/docs/latest/install/aws/aws-terraform.html#customize-the-deployment) to run terraform apply manually.
- Replace the values from terraform.tfvars in assets.zip to terraform.tfvars on your local and increase the count to 3 for masters, workers & etcd.
- Terraform apply will fail saying => Error creating AutoScaling Group: AlreadyExists: AutoScalingGroup by this name already exists - A group with the name manualtest-cluster0705-workers already exists

## Anything else we need to know?

**Comment by Quentin-M** [comment]
Could you come up with a minimum reproducing case outside of Tectonic, and file the issue [upstream](https://github.com/terraform-providers/terraform-provider-aws) (if not already existing)?

**Comment by colhom** [comment]
@gopilal I'm guessing that this happens because the terraform state is lost between the GUI install and the second `terraform plan/terraform apply` step. You can verify this by running `terraform show` once you have your terraform environment set up for attempting to scale the cluster. If you get nothing back, that means that terraform has no knowledge of the current state of the cluster resources, which means (among other things) it will try to create resources that already exist. 

@Quentin-M what would the best way to capture the terraform state from the GUI install and make it available to terraform at a later date? Is it packaged anywhere in the assets bundle?

**Comment by Quentin-M** [comment]
@colhom It is :) This is how 'terraform destroys' are possible.

**Comment by colhom** [comment]
Related https://github.com/coreos/tectonic-installer/issues/1297
