### ISSUE TITLE
[alpha] openstack: Where are the assets-*zip files files? => No rule to make target `localconf'

### ISSUE THREAD

**Issue by stefanandres** [coreos/tectonic-installer#150]
In https://github.com/coreos/tectonic-installer/blob/master/Documentation/install/openstack/openstack-terraform.md it says 
>Copy the assets-<cluster-name>.zip to ./boot/<cluster-name> or
Create a config.tfvars file in the root of the repo having the following properties set. All other options can be left empty.

But I cannot find this zip file anywhere. In https://github.com/coreos/tectonic-installer/blob/master/Documentation/platform-lifecycle.md it says to find them from the installer tarball, but there are not there as well.

When just creating the config.tfvars file and doing the make it errors out with (well, nothing is in the build/<clustername>/ dir):

```
sandres@sandres ~/k8s/tectonic-installer(master) $ make PLATFORM=openstack/neutron CLUSTER=testing localconf
Using TerraForm binary [/usr/local/bin/terraform]
Using build directory [/Users/sandres/k8s/tectonic-installer/build/testing]
make: *** No rule to make target `localconf'.  Stop.
```

**Comment by s-urbaniak** [comment]
Thanks for reporting the issue. Indeed the openstack documentation was lagging behind, sorry about that and this is being fixed in https://github.com/coreos/tectonic-installer/pull/157 already fixes the documentation.

Regarding your concrete error, please use `make PLATFORM=openstack/neutron CLUSTER=testing localconfig` (not `localconf`)
