### ISSUE TITLE
Automatically generate tfvars examples as part of variable generation

### ISSUE THREAD

**Issue by robszumski** [coreos/tectonic-installer#153]
Today we have code that reads the variable descriptions and outputs docs like https://github.com/coreos/tectonic-installer/blob/master/Documentation/variables/config.md.

We should take this one step further and use the same defaults and descriptions to generate the example files.

 - output comment headers to group fields together. this keeps AWS stuff together, general Tectonic stuff together, etc.
 - output the variable descriptions as comments near the variable itself
 - set defaults
 - comment out anything that doesn't have a default but keep it in the file to indicate what you _can_ configure and its format
 - bonus points: support the ability to flag something as required separately from having a default, so we can set defaults for things that aren't required. right now the logic is `if (has default) required=true`. this will make it much easier to suggest how to use things.

**Comment by s-urbaniak** [comment]
I would like to tackle this in conjunction with #230 and auto-generate the following files:
```
./platforms/azure/terraform.tfvars.example
./platforms/aws/terraform.tfvars.example
./platforms/openstack/nova/terraform.tfvars.example
./platforms/openstack/neutron/terraform.tfvars.example
```

Regarding the last part (bonus point): terraform does have a notion of separating optional and required values as per [1] but the hard reality shows that declarations without default values (required as per terraform) do not play well with ternary operators hence we often leave them as empty string `""`.

This leads to the situation that we also have mixed rules, i.e. `tectonic_ca_cert` defaults to empty-string `""` and indeed is optional.

Since the vast majority of variables actually is required I suggest to interpret a magical `(optional)` in the description for a variable to be considered optional.

[1] https://www.terraform.io/intro/getting-started/variables.html#defining-variables
