### ISSUE TITLE
tests: Restructure /tests folder

### ISSUE THREAD

**Issue by mxinden** [coreos/tectonic-installer#1531]
I would like to restructure the `/tests` folder. I would suggest a structure like the following:
```
/tests
/tests/smoke
/tests/smoke/vars          # tfvars files
/tests/smoke/spec          # Ruby spec files
/tests/smoke/lib           # Ruby helper code
/tests/smoke/cluster-tests # Golang smoke tests
```

In addition I would like to move the `/tests/jenkins-jobs` folder into `/scripts/jenkins-jobs` so we can move Jenkins scripts in there, that are not test related.

//CC @alexsomesan

**Comment by squat** [comment]
@mxinden this is  a good time to move the ruby (formerly bash) lib code that sets up the test infrastructure OUT of the `smoke` sub-directory; every test type (smoke, e2e, QA, conformance etc) relies on this tooling and it is no longer correct to label it as smoke. I am also not fully convinced by `cluster-tests` directory since not all of the golang code tests the whole cluster, at least not any more so than the ruby spec tests do; we now have automated QA tests that are compiled into that binary.

**Comment by mxinden** [comment]
@squat How about this structure:
```
/tests
/tests/lib                 # Ruby helper code & Golang code that can be reused in different test types
/tests/smoke
/tests/smoke/vars          # tfvars files
/tests/smoke/spec          # Ruby spec files specifying the **smoke** tests with the help of code in `/tests/lib`
/tests/conformance
/tests/conformance/spec    # Ruby spec files specifying the **conformance** tests with the help of code in `/tests/lib`
...
```
