### ISSUE TITLE
Tectonic Ingress - no –tec ending ELB

### ISSUE THREAD

**Issue by kubebc** [coreos/tectonic-installer#2085]
**Tectonic version**: 1.7.1-tectonic.2

Hi, team,

I’m trying to use Tectonic Ingress following your guide here. 
https://coreos.com/tectonic/docs/1.7.1-tectonic.2/admin/ingress.html

There should be a Tectonic ELB ending with –tec according to this. But I cannot find it in AWS dashboard. What did I miss here? Thanks!
"
Test your rules
For Tectonic AWS, add a DNS CNAME record hello.example.com to your Tectonic ELB. It ends in -tec and can be found on your AWS dashboard.
"

Best wishes,
Brant

**Comment by squat** [comment]
Brant,
Those docs are a little out of date. Tectonic no longer creates any load balancers ending in `-tec`. There are three load balancers created by default `-int`, `-ext`, and `-con`, which are respectively an internal load balancer for the API, an external load balancer for the API, and an external load balancer for the console. Additionally, Tectonic automatically created several Route53 records for you. By default, `<cluster_name>.<base_domain>` will point to the console load balancer, while `<cluster_name>-api.<base_domain>` will point to the external API load balancer.

**Comment by kubebc** [comment]
Thanks squat!
My goal is to use the Tectonic Ingress Controller for our applications.
I've already created a ingress kind successfully. 

**So which ELB should I map my preferred DNS CNAME record to?** seems like none of them are working.

Btw, my real situation is more like this. “my tectonic stack is built in aws account A, but my domain is controlled in aws account B rout53.”

Best wishes,
Brant

**Comment by squat** [comment]
@kubebc hmm the ELB is not working? Are you able to `kubectl get nodes` and also are you able to reach the Tectonic console? If so then the load balancers are working. In order to map a DNS name to a service, you need to point the CNAME record the the load balancer. This must be in the same AWS account otherwise AWS cannot connect the two for you. If they absolutely cannot be in the same account then you will need to use IP addresses for the DNS record rather than the ELB object itself please note that this use-case is not supported by Tectonic. If you choose this option, it is crucial that you do not use the ELB's IP address directly since these are liable to be rolled every few weeks, causing your DNS records to be out of date. Instead, you will need to find the public IP addresses of your master nodes and configure the Route53 record to point to these values.

**Comment by robszumski** [comment]
@kubebc Can you load the Console? If so, the Ingress is working correctly.

I filed a PR to update that doc with the updated nameing. The rest of it is still accurate and should get you a working Ingress rule you can use with your application.

On AWS, I have a similar DNS set up as you, with the separate accounts. What you can do is create an `alias` record at the root of the domain to the cname of the ELB, which you can find with the `-con` suffix.

**Comment by joshix** [comment]
fixed in https://github.com/coreos/tectonic-docs/pull/75; propose to close

**Comment by sym3tri** [comment]
Looks like docs were fixed.
