### ISSUE TITLE
Tectonic ingress, always return Unauthorized

### ISSUE THREAD

**Issue by johnzheng1975** [coreos/tectonic-installer#2106]
BUG REPORT  

Refer to: https://coreos.com/tectonic/docs/latest/admin/ingress.html
Not work

## Versions

* Tectonic version ([release](https://github.com/coreos/tectonic-installer/releases) or commit hash): 1.7.3
* Terraform version (`terraform version`): 
* Platform (aws|azure|openstack|metal): AWS

## What happened?
I installed tectonic ingress
access the url: https://qa.***.com/authentication/swagger-ui.html
It always return **Unauthorized** 
(HTTP/1.1 401 Unauthorized)

## What you expected to happen?
It should return http page with http response status 200

## How to reproduce it (as minimally and precisely as possible)?
Always

## Anything else we need to know?

In AWS route53, qa.***.com will point to CNAME which same CNAME iwth platform-api
.***.com

**Comment by joshrosso** [comment]
Hi @johnzheng1975 

It appears your CNAME record, `qa.fitstationmini.com` is pointing to the Kubernetes API server, `platform-api.fitstationmini.com`, rather than the Tectonic console.

The tectonic console is likely a record such as `platform.fitstationmini.com`.

It should be an A record setup as an ALIAS pointing to an ELB with a naming structure similar to `platform-con-*`.

**Comment by johnzheng1975** [comment]
Resolved, thanks.
