### ISSUE TITLE
ensure required roles docs are updated

### ISSUE THREAD

**Issue by sym3tri** [coreos/tectonic-installer#229]
https://coreos.com/tectonic/docs/latest/install/aws/requirements.html#privileges

Follow the link to the policy json file.

**Comment by alexsomesan** [comment]
This seems to only affect documentation. I suggest we tackle this after the Friday code freeze (but before the release on Wednesday).

**Comment by sym3tri** [comment]
@alexsomesan bump. Any chance we can get this updated by EOD?

**Comment by alexsomesan** [comment]
I'm on it today.

**Comment by robszumski** [comment]
@bison did you have comments on this?

**Comment by bison** [comment]
I opened https://github.com/coreos/tectonic-installer/pull/611 because that prevented me from even getting started. There are definitely other things that need to get updated though -- for one, destroy doesn't work because the current policy doesn't grant delete permissions.

I think there are other issues, but I don't have an exhaustive list or anything. I just gave this a quick try with the RC today. Happy to help test when the time comes.

**Comment by alexsomesan** [comment]
@sym3tri @bison I'm doing test builds and adjusting the policy to get a successfull apply. Still not there yet, but making progress. Quite a couple of permissions are missing.

**Comment by alexsomesan** [comment]
Status update: this is tacking way longer than originally estimated.
It's a slow churn of updating the policy and then doing a cycle of `plan` > `apply` > `destroy` for every missing permission found.
I'm running into a lot of missing permissions compared to our existing policy. Terraform also makes calls to unrelated services under the hood, so for example when creating an ELB, it might also call IAM (for certificates) or EC2. This adds a whole set of unexpected permissions we need to include.

**Comment by sym3tri** [comment]
should be fixed in https://github.com/coreos/tectonic-installer/pull/756
