### ISSUE TITLE
AWS: Can't bootstrap cluster without private endpoints

### ISSUE THREAD

**Issue by aknuds1** [coreos/tectonic-installer#2419]
## Versions

* Tectonic version ([release](https://github.com/coreos/tectonic-installer/releases) or commit hash): 19a6e0b6b756a391d77f40d22a7684f7f700fa25
* Terraform version (`terraform version`): v0.10.8
* Platform (aws|azure|openstack|metal): aws

## What happened?
I try to create a cluster with Tectonic Installer on the command line (`CLUSTER=codersociety PLATFORM=aws make apply`) configured to disable private endpoints (`tectonic_aws_private_endpoints = false`). This causes an error in detect-master.sh during the earliest stages of cluster bootstrapping, on account of there being no load balancer called tectonic-test-int:
```
An error occurred (LoadBalancerNotFound) when calling the DescribeInstanceHealth operation: There is no ACTIVE Load Balancer named 'tectonic-test-int'
```

## How to reproduce it (as minimally and precisely as possible)?
Use a configuration similar to the following (in terraform.tfvars), disabling `tectonic_aws_private_endpoints`:

```
tectonic_admin_email = "me@example.com"
tectonic_admin_password = "password1234"
tectonic_aws_assets_s3_bucket_name = "tectonic.kopscluster.com"
tectonic_aws_extra_tags = {"cluster" = "tectonic-test"}
tectonic_aws_private_endpoints = false
tectonic_aws_public_endpoints = true
tectonic_aws_region = "eu-central-1"
tectonic_aws_ssh_key = "me"
tectonic_base_domain = "kopscluster.com"
tectonic_cluster_name = "tectonic-test"
tectonic_license_path = "tectonic-license.txt"
tectonic_pull_secret_path = "config.json"
tectonic_master_count = "1"
tectonic_worker_count = "2"
tectonic_aws_profile = "coder-society"
tectonic_self_hosted_etcd = "enabled"
```

**Comment by squat** [comment]
We were aware of issues with disabling private endpoints and created https://github.com/coreos/tectonic-installer/pull/2392 for that reason. @s-urbaniak can you PTAL?

**Comment by squat** [comment]
Indeed, we are hardcoding a loadbalancer in detect-master.sh:

https://github.com/coreos/tectonic-installer/blob/master/modules/aws/master-asg/resources/detect-master.sh#L28

**Comment by squat** [comment]
OK, looking more into this: this issue occurs because we recently added `-o pipefail` to the detect-master.sh script. This causes a previously undetected issue to break bootstrapping for clusters with no private-endpoints.

`API_HEALTHY=$(aws elb describe-instance-health --region="$REGION" --load-balancer-name "$CLUSTER_NAME-int" | jq -r '[ .InstanceStates[] | select(.State | contains("InService")) ] | length > 1')`
is hardcoded to use the internal loadbalancer. Without pipefail, this aws command would 404 and the error would get swallowed by the pipe. `API_HEALTHY` would never be true, even if the API was actually healthy, so the rest of the script would run.

Now, since the pipefail option is set, that command correctly errors out and the script execution is aborted.

We simply need to template the loadbalancer name based on whether private endpoints are enabled or disabled.

**Comment by squat** [comment]
@aknuds1 I just wrote a patch to fix this issue. I tested locally building a cluster with private endpoints disabled and everything looks good. Please have a go building with this commit.

**Comment by aknuds1** [comment]
@squat Trying now

**Comment by aknuds1** [comment]
@squat Ugh it failed :(

```
* aws_launch_configuration.master_conf: Error creating launch configuration: ValidationError: 1 validation error detected: Value 'ewogICAgImlnbml0aW9uIjogewogICAgICAidmVyc2lvbiI6IC[...]' at 'userData' failed to satisfy constraint: Member must have length less than or equal to 21847
	status code: 400, request id: ab937560-cb96-11e7-9a80-a39dba118715
```

Any idea what causes this? Are you on Slack btw, e.g. the Kubernetes workspace? Would be easier to communicate like that.

**Comment by squat** [comment]
@aknuds1 this should be fixed now. Please re-open if needed
