### ISSUE TITLE
GUI: last screen should have additional explanations

### ISSUE THREAD

**Issue by sym3tri** [coreos/tectonic-installer#363]
Some things we are missing. Maybe link to a website doc with all of these things:

- [ ] How to generate your kubeconfig
- [ ] How to shutdown the installer
- [ ] What to do with the assets you downloaded
- [ ] How to destroy your cluster

**Comment by meghanschofield** [comment]
Current state:

<img width="526" alt="screen shot 2017-06-22 at 4 20 46 pm" src="https://user-images.githubusercontent.com/3373315/27460221-4fccbb6c-5767-11e7-9f3c-e27620507e8e.png">

I'll be taking a look at a revamp of this page! Updates coming soon.

**Comment by rithujohn191** [comment]
Any updates on this @meghanschofield. We were trying to scope this out for the next sprint.

**Comment by meghanschofield** [comment]
Ed and I caught up on this task just now. Two things are needed:

1. A new cleaner screen for Installation Complete. 
- with "go to console" primary button
- with "be sure to download assets" secondary button (and related reasons)
- removing: back, start over, tutorial and kubctl stuff. Tutorial and kubctl stuff will be moved to the first page in the console. 

2. Clicking "Go to my console" takes users to a Quick Start page to include:
- set up kubectl (new tectonic specific doc needed that explains setting up kubectl in the console and in general)
- set up your first application tutorial
- information on how to destroy a cluster
- a section for more advanced resources

I'll get work on this stuff asap!

**Comment by meghanschofield** [comment]
Updated installer mock for the Installation Complete Page:

<img width="532" alt="screen shot 2017-07-19 at 4 10 58 pm" src="https://user-images.githubusercontent.com/3373315/28393674-f72e3c7e-6c9c-11e7-8f30-a9396e7ee46f.png">

##### Callouts and notes:

<img width="649" alt="screen shot 2017-07-19 at 4 11 07 pm" src="https://user-images.githubusercontent.com/3373315/28393675-f89c2ab2-6c9c-11e7-9386-b0e66b5153f0.png">

##### General Notes
- Users can still "go back" by clicking the link in the side nav. 
- This gives users a way to close the installer


##### Content for easy cut and paste
All set! Now you can access the Tectonic Console. Once there, you’ll be able to configure kubectl, and deploy your first application to the cluster.

The Tectonic Console gives you an easy-to-navigate view of your cluster. 

Cluster assets are important, save them now! 

Download and keep your cluster assets in a safe space. These are needed to destroy, replicate or quickly reinstall.

**Comment by meghanschofield** [comment]
![artboard](https://user-images.githubusercontent.com/3373315/28486002-a756316a-6e32-11e7-822d-b4f5cc4d9050.png)

This is a quick pass at the possible Quick Start page. 
**This isn't final** 
Tony will iterate on it, but you can see the beginnings

**Comment by kyoto** [comment]
The “I’m finished” button is intended to close the tab, but the browser won’t actually let JS close the tab because the wasn’t opened by the same script.

**Comment by tlwu2013** [comment]
Hi @kyoto , 

Here's the updated mock for the final screen:
![0803_2017__installation complete](https://user-images.githubusercontent.com/5903705/28982139-8f19b068-7909-11e7-8c2b-6e14133d1c17.png)

And the spacing:
![0803_2017__installation complete_spacing](https://user-images.githubusercontent.com/5903705/28982145-94440688-7909-11e7-8059-df12dd7f3e81.png)

And just FYI, here's the First-Time-Use quick start guide design on the Console side:
![cluster status - 0803_2017_v4](https://user-images.githubusercontent.com/5903705/28982180-b776d874-7909-11e7-84ad-915630dd15fb.png)

*Console JIRA:
https://coreosdev.atlassian.net/browse/CONSOLE-139

Since we move some stuffs from installer to console, now the final screen only shows two CTAs in sequence to hint users download the assets before going to the console.

And during our internal product team sync, we discussed if we need to keep "Back" and "Start Over" text link. The conclusion we reached is that we don't need both of them anymore.
It's because:
1.  The main reason user has to click on "Back" on the final page is for "download assets". Now we ask users to download before going to Console. So the importance of "Back" link is not that obvious (plus, they can still go back from the side nav).

2. The important of the "Start Over" here is not obvious either. The primary user path on this page should be download asset and then go to console. The only thing could be is to re-apply Terraform if users are going to launch multiple cluster in sequence. But even so, "Start Over" link is not useful for this flow. So we can take it out as well.

Please let me know if you have any follow-up questions, as always, thanks Andy!

**Comment by kyoto** [comment]
@tlwu2013 @ggreer Installer side of this is done and I think the Console side is done too, so I'm closing this issue. Please reopen if there is still more to do on the Console side.
