### ISSUE TITLE
GUI: Surface all relevant version information

### ISSUE THREAD

**Issue by sym3tri** [coreos/tectonic-installer#364]
It would be nice if the GUI installer surfaced the following info:

- What version you are currently using
- Whether or not a new version is available
- What version of Terraform the installer is compatible with
- All links go to specific versioned docs (i.e. not `docs/latest`)

**Comment by meghanschofield** [comment]
I'm on it. Seems like stuff for the first page. A few questions:

1. Why does this help users? is it really for repeat users or first time?
2. IF there is a new GUI installer version available, do we link to that from older ones? 
3. Why would they ever want to use an old one? How would they get to the old one?
4. For links to the versioned docs. I assume that's just for the options users need, but do we need to give users a way to easily jump to other versioned docs? (maybe for comparison?)

I always worry about optimizing for edge cases, b/c it gives the other 99% of users too much to contemplate when it's not needed. So, is this an interim thing? or a forever thing, b/c of how Terraform works?

Thanks @sym3tri !

**Comment by robszumski** [comment]
I'll take a swing at some of these:

> What version you are currently using
> Why does this help users? is it really for repeat users or first time?
> Whether or not a new version is available

**Supportability:** when encountering issues with the installer, this is the first thing to help everyone get on the same page to triage
**Repeat usage:** if you downloaded a while ago and want to see what has changed since this (installation-wise) you can match this up to release notes
**First time:** someone may have signed up for your company and sent you an out of date installer. Mostly related to below:

> If there is a new GUI installer version available, do we link to that from older ones?

This should always be safe, as we're always fixing bugs, making it more stable, and adding new platforms.

> Why would they ever want to use an old one? How would they get to the old one?

If they want to set up a cluster exactly as they did a while ago.  They would need to swap out the version number in the link: https://releases.tectonic.com/tectonic-1.5.6-tectonic.1.tar.gz aka we don't make this super easy on purpose. We'd rather you run the latest.

> What version of Terraform the installer is compatible with

For this, we should start listing it with the release notes. And then link to them from wherever we display the current version. Something like `Version 1.5.6-tectonic.1 (release notes)` or similar.

> All links go to specific versioned docs (i.e. not docs/latest)
> For links to the versioned docs. I assume that's just for the options users need, but do we need to give users a way to easily jump to other versioned docs? (maybe for comparison?)

This is mostly an intangible UX thing that the engineering team will swap out. At the top of each doc there is a dropdown to swap to an older version. Take a look to see if you think this meets needs.

> I always worry about optimizing for edge cases, b/c it gives the other 99% of users too much to contemplate when it's not needed.

This can be as minimal as we want it to be. Think of a small treatment in the nav bar or adding a footer that has the version + link to release notes + versioned docs. If there is a later version, note that. Conversely, it could be a huge banner on step 1 that really suggests that you use a newer version.

> So, is this an interim thing? or a forever thing, b/c of how Terraform works?

We will always be beholden to the version of Terraform we support/test against, and that won't be going away any time soon. Folks might be using newer or older versions for other projects at their companies. We'll always ship the version that they need in the download, we just need to make sure they use it. That's mostly a docs problem however.

**Comment by sym3tri** [comment]
> 1. Why does this help users? is it really for repeat users or first time?

Mostly for repeat users who have already downloaded an old version. We should let them know there is a new one available so they can have the latest & greatest.

We will always _require_ a specific version of Terraform. If they have something else on their system they will run into issues if they try to us it.

These could both be accomplished via docs, but the intent is to surface it more prominently in case users aren't checking the docs every day.

> 2. IF there is a new GUI installer version available, do we link to that from older ones? 

I think that makes sense. Many existing software applications do this. The pattern is usually a banner that appears at the top with phrasing like: "A newer version is available, click here to download.".

> 3. Why would they ever want to use an old one? How would they get to the old one?

There are customer use-cases where they are not ready to use the latest, or the latest has known bugs, or they deleted/lost the original old installer used to provision a cluster and need one that matches their cluster version to help with deletion, or they want to maintain consistent versions of multiple clusters, etc.

Users can always download old versions using the version selector in our docs:

![screenshot from 2017-04-26 13-44-32](https://cloud.githubusercontent.com/assets/224222/25456135/e3159276-2a86-11e7-874a-680b78be7edd.png)

> 4. For links to the versioned docs. I assume that's just for the options users need, but do we need to give users a way to easily jump to other versioned docs? (maybe for comparison?)

No UX changes required here, just updating the links we use in the installer. 

ex:
Want to avoid a 1.4 installer linking to "latest" docs which are actually "1.5.6" docs. That is today's behavior and would cause confusion.

https://coreos.com/tectonic/docs/latest/install/aws/index.html (this constantly changes with each release)
vs
https://coreos.com/tectonic/docs/1.5.6-tectonic.1/install/aws/index.html (today is same as latest, not true after the next release is cut)
vs
https://coreos.com/tectonic/docs/1.4.7-tectonic.1/install/aws/index.html (an old version w/a fixed URL)

**Comment by meghanschofield** [comment]
Got it. Thanks everyone! I'll get to work on this business.

**Comment by meghanschofield** [comment]
Here are some mocks! If these pass muster @sym3tri - I'll mark them up with dimensions and callouts. 

### Version added (top right nav bar)
![installer_version](https://cloud.githubusercontent.com/assets/3373315/26077498/1799dd2e-3971-11e7-9399-b1c14949d875.png)

### If a new version is available - the underlined link takes you to the docs for that most recent version
![installer_newversionavailable](https://cloud.githubusercontent.com/assets/3373315/26077532/3600f7a2-3971-11e7-94a5-7e1096d2126d.png)

There is a lot of other stuff updated here, but these mocks are only to show the new version. I'll make issues for the other new bits. Thanks!
