### ISSUE TITLE
publish docs on how to add new platform

### ISSUE THREAD

**Issue by sym3tri** [coreos/tectonic-installer#46]
Should include architecture diagram, TF conventions, directory structures, module usage, etc.

**Comment by alexsomesan** [comment]
Will tackle this latest by early next week. I'm traveling tomorrow.

**Comment by sym3tri** [comment]
@alexsomesan I'm assigning as much of the docs stuff as possible to @zbwright. I co-assigned to you so she knows who to go to for questions.

**Comment by alexsomesan** [comment]
Got it, @symetri
Glad to help then.

**Comment by zbwright** [comment]
hey @alexsomesan -  would you like to set up a time to talk through this on slack? I can be available for you as early as 8am here (5pm your time).

**Comment by alexsomesan** [comment]
Started this as a google doc because I think it makes review iterations a bit easier.
https://docs.google.com/document/d/1xraeD1_Juqb_jeUjA222OAEBHYWjpbPal93b2atghNc/edit#heading=h.w2o9hrfxw6qv

Once it reaches a "good enough" state I will export that as markdown and add it to the repo under `./Documentation/dev`

**Comment by Quentin-M** [comment]
@alexsomesan @sym3tri Can we integrate this somewhere? Neither Rob and I have access to it.

**Comment by s-urbaniak** [comment]
@Quentin-M @sym3tri you should have access now to https://docs.google.com/document/d/1xraeD1_Juqb_jeUjA222OAEBHYWjpbPal93b2atghNc/edit#heading=h.w2o9hrfxw6qv.

**Comment by sym3tri** [comment]
moved to jira https://coreosdev.atlassian.net/browse/INST-191
