### ISSUE TITLE
documentation: talk about node groups or pools

### ISSUE THREAD

**Issue by philips** [coreos/tectonic-installer#48]
A very common ask is for heterogeneous node layouts. This should be possible with our module refactor. For example on Azure you could create "worker-gpu" and just change the machine type: https://github.com/coreos-inc/tectonic-platform-sdk/blob/master/platform-azure/main.tf#L58

**Comment by sym3tri** [comment]
Closing b/c this epic is still being flushed out elsewhere.

**Comment by chuckbutler** [comment]
I realize i'm late to the party but can we get a signpost to the epic? This is highly attractive to anyone using tectonic right now, and will change how we form clusters. Node Pools / Groups are a feature we're feeling the pain of missing.

**Comment by sym3tri** [comment]
Thanks for the feedback @chuckbutler. We're trying to figure out the best way to implement the feature & this issue was closed only b/c it's not immediately actionable. It needs to be broken up into smaller chunks. 

It's definitely a high-priority and on our roadmap, but I don't have any dates for you at this time. If you can post specific use-cases & what you'd like to see in this feature it'd be helpful for our planning.

/cc @robszumski

**Comment by peay** [comment]
@sym3tri is this still on the road map and/or being discussed elsewhere? We have similar use cases where we want a couple high-performance node (e.g., GPU or lots of memory) only for some deployments, and want to use taints/tolerations/labels to control what gets scheduled where.

**Comment by sym3tri** [comment]
@peay yes it is, but we need to first finishing some refactoring (in-progress) to may the way we provision nodes more flexible in general. This is definitely something we'd like to support.
