### ISSUE TITLE
Setup automated builds + smoke tests 

### ISSUE THREAD

**Issue by Quentin-M** [coreos/tectonic-installer#61]
As soon as possible, we should come up with a plan and execute on running:

- [ ] Smoke tests for every PR
  - [x] `terraform fmt`
  - [ ] `terraform validate`
  - [ ] orphan variables / parameters check 
  - [x] `terraform apply` on AWS with basic parameters
- [ ] Nightly builds
- [ ] Daily scenarized tests (new VPC, existing VPC, external etcd, self-hosted etcd, ...)
- [ ] E2E tests

For the scenarized / E2E tests, we should sync with @pbx0, @ethernetdan and @bison to see how we can integrate with the existing tooling.

I think it could be interesting to have something like:
```
tests/scenarios/
test/scenerarios/aws-existing-vpc.tfvars <--- Input variables used to run tectonic-terraform-sdk
test/scenarios/aws-existing-vpc.tf      <--- Extra infrastructure to deploy before running 
tectonic-terraform-sdk (e.g. existing vpcs), output is used to substitute variables in associated .tfvars
test/scenarios/aws-self-hosted-etcd.tfvars
[...]
```

We have set up a public Jenkins to run all these:
- https://jenkins-tectonic-installer.prod.coreos.systems/
- https://jenkins-tectonic-installer-public.prod.coreos.systems/

**Comment by pbx0** [comment]
I would be interested in making this a supported test platform in pluton. Its an open-question of how we would implement this and if pluton could be made flexible enough to deal with these platform specific scenarios. Some thoughts if anyone else is interested in this route.

In pluton, tests are defined as a go function with a signature `func(c *Cluster)` This `Cluster` is a platform-independant abstraction for managing a k8s cluster that also has the equivalent of a golang  `testing.T` embedded for logging output, skipping, having subtests, ect. 

Because test functions test against this abstraction, we need a declarative way to describe those testing scenarios if we want this integration to work.

Currently a test is declared:
```
pluton.Test{
        Name: "test.name",
        Run:  f,
        Options: pluton.Options{
                SelfHostEtcd:   false,
                InitialMasters: 1,
                InitialWorkers: 1,
        },
}
```
This is enough to setup a cluster and run a test. Global flag options collect the rest of the variables needed to run this platform such as gce specific variables and the bootkube container to use. The platform to use is implicit right now. If we wanted to implement a tectonic-sdk platform into this framework we'd need to write some code that bridges using the tectonic-sdk to create a cluster and implement a `Cluster` for the harness to pass to a test. Also, we'd have to find a way to make test declaration syntax powerful enough for this platform to implement above scenarios. The test declaration syntax can definitely have tons of platform specific configurations, however, the tests should be abstracted. If this is not ideal for this type of test work then i'd say this is definitely not the right framework.

Just some thoughts. If it sounds interesting at all maybe someone could write out in a psuedo-ish way how one might declare a `Test` for this platform. 

cc @marineam

**Comment by marineam** [comment]
Since terraform expects to start up machines it takes the place of at least some of what the platform cluster code does. So to integrate well the underlying test harness changes quite a bit. I'm currently experimenting with this and will have a proof of concept in the next few days.

**Comment by sym3tri** [comment]
@Quentin-M let's break this into smaller issues.

**Comment by Quentin-M** [comment]
Agreed. This big one was created during the bootstrapping phase.
