### ISSUE TITLE
single source of truth for input variables

### ISSUE THREAD

**Issue by sym3tri** [coreos/tectonic-installer#636]
To enable better testing.

We will discuss in meeting and fill out details here

**Comment by kans** [comment]
tfvars are the source of truth, and we should remove all special logic from the backend so that there is no intermediate representation between the front end and terraform.  The frontend will generate a versioned tfvars json blob and give it to terraform untouched.  Reference blobs will be used for frontend tests and smoke tests alike.  The blob will also be shoved into the cluster as a configmap so that operators can know what is going on.

Related issues:
* #642 
* #643 
* $644

**Comment by sym3tri** [comment]
I believe this is already complete and we plan to refactor this anyway
