### ISSUE TITLE
Modify cert generation to use SAN not CN

### ISSUE THREAD

**Issue by robszumski** [coreos/tectonic-installer#656]
https://github.com/coreos/tectonic-forum/issues/118 references changes to Chrome that deprecate CNs in favor of SANs.

Update our certificate generation to handle this more gracefully.

**Comment by colhom** [comment]
The installer now uses terraform to generate the console cert [here](https://github.com/coreos/tectonic-installer/blob/23d530e3471b37e5a39539305eb2d2bf89e69af7/modules/tectonic/assets.tf#L55)

I'm assuming terraform does the right thing here and includes the ingress DNS name as a SAN rather than the CN? \cc @bison

**Comment by bison** [comment]
Yep, 1.6 with Terraform should be using SAN:
https://github.com/coreos/tectonic-installer/blob/master/modules/tectonic/crypto.tf#L22-L35

**Comment by robszumski** [comment]
Awesome, with a relevant comment even. Closing.
