### ISSUE TITLE
Errors during terraform

### ISSUE THREAD

**Issue by pingthings** [coreos/tectonic-installer#682]
This is a pristine install so the profiles weren't persisted from any previous install.  Looks like these profiles get generated earlier in the installation and then attempts to do it again and fails since they're already generated.

2 error(s) occurred:

* module.masters.aws_iam_instance_profile.master_profile: 1 error(s) occurred:

* aws_iam_instance_profile.master_profile: Error creating IAM instance profile btrdb-master-profile: EntityAlreadyExists: Instance Profile btrdb-master-profile already exists.
	status code: 409, request id: 51bc5104-3765-11e7-a21d-3d0ace72e7d2
* module.workers.aws_iam_instance_profile.worker_profile: 1 error(s) occurred:

* aws_iam_instance_profile.worker_profile: Error creating IAM instance profile btrdb-worker-profile: EntityAlreadyExists: Instance Profile btrdb-worker-profile already exists.
	status code: 409, request id: 51c35685-3765-11e7-8e73-7f47d6edec0c

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

**Comment by ShakataGaNai** [comment]
Did you run this installer in an environment where you had previously installed Tectonic? I happened to run into this same issue on an environment that I had manually cleaned up. Did an `aws iam list-instance-profiles` and `aws iam delete-instance-profile --instance-profile-name` with the two bad profiles and I was able to continue.

**Comment by pingthings** [comment]
Took a bit of searching since we also had done a manual clean up and instance-profile aren't exposed in the AWS console interfaces (or at least we didn't find it).  We finally figured out that an earlier run left those hidden-profiles intact.

**Comment by JoshuaKolden** [comment]
I would recommend re-opning this issue and specifically addressing it in the installer.  As far as I can tell with no other information in the console the cause of the error is completely opaque to the user.  We ran into this problem as well, and found no solution after many attempts until we finally found this github issue.  The tectonic-installer docs give the impression that the process is either idempotent or at least safely repeatable, and this error makes that not true in a very obscure way.

I don't know how terraform works, but the solutions I recommend are:

a) For the destroy cluster command destroy everything that would have been created even if the installation did not finish, because the destroy operation may need to clean up resources that were created on a previous run that went further, or may for other reasons (bugs, etc.) have incomplete information about what tasks were completed during the most recent build.

b) Do an initial trivial check that the cluster is already built and running and exit early if it is, otherwise when building the cluster destroy all conflicting duplicates as they are encountered.

Although personally I'd prefer a much more robust idempotent installation process, these two steps seem like a quick and dirty way to address this issue without expecting the user to have magical insight to hidden errors.
