### ISSUE TITLE
platforms/*: install the default storage classes

### ISSUE THREAD

**Issue by philips** [coreos/tectonic-installer#711]
Since we don't run the add-on manager we don't' install the default storage classes. We should do this!

- [AWS](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/storage-class/aws/default.yaml)
- [OpenStack](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/storage-class/openstack/default.yaml)
- [etc](https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/storage-class)

cc @polvi

**Comment by alexsomesan** [comment]
Thanks for pointing this out. Didn't realise we were missing these.

**Comment by alekssaul** [comment]
VMware: https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/storage-class/vsphere/default.yaml 

I believe default storageclass integration (at least in VMware platform) requires kubelet/api/controller-manager to be running with `--cloud-provider` flag. https://github.com/coreos/tectonic-installer/issues/84 & https://github.com/coreos/tectonic-installer/issues/51

**Comment by bleggett** [comment]
This is not fixed in `1.7.5-tectonic.1`, and I do not think it has actually been fixed.

I had to manually deploy the default [AWS storage class](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/storage-class/aws/default.yaml) to my AWS based tectonic cluster before any PVCs would work, and verified with `'kubectl get storageclasses` that none of the default StorageClass objects were deployed by the tectonic installer.

**Comment by sym3tri** [comment]
@bleggett You're right this has not yet been resolved. Reopening.

**Comment by sym3tri** [comment]
We're working on the next generation of the installer which will integrate Tectonic and Open Shift. We'll consider this for that project, but will not be adding this feature in this repo. 

See our blog for any additional details:
https://coreos.com/blog/coreos-tech-to-combine-with-red-hat-openshift
