### ISSUE TITLE
Docs: Are there any existing VPC changes with TF?

### ISSUE THREAD

**Issue by zbwright** [coreos/tectonic-installer#764]
Is this still accurate? Or do we create the gateways et al with TF?
https://github.com/coreos/tectonic-installer/blob/master/Documentation/install/aws/requirements.md#using-an-existing-vpc

**Comment by sym3tri** [comment]
@alexsomesan can you please provide guidance. I believe the current docs are accurate but am unsure about:

_"Public subnets have a default route to the Internet Gateway and should auto-assign IP addresses. Private subnets have a default route to a default gateway, such as a NAT Gateway or a Virtual Private Gateway."_

**Comment by alexsomesan** [comment]
@sym3tri That phrase sounds correct, but to be 100% accurate I would tweak the IP address part to: "and should auto-assign public IP addresses." (because private ones always get auto-assigned no matter what kind of subnet).

I should go through the whole document once as I spotted some other places where we can clarify better.

**Comment by zbwright** [comment]
hey @alexsomesan -  I'll wait on making any changes to this doc until after you have a chance to take a pass through it. thank you.

**Comment by zbwright** [comment]
@alexsomesan this one too, please.
