### ISSUE TITLE
publish upstream e2e test results to testgrid

### ISSUE THREAD

**Issue by sym3tri** [coreos/tectonic-installer#979]
Once our e2e tests up and running we need to publish the results to the upstream TestGrid system. It should just involve pushing the results to an s3 bucket, and registering that with TestGrid.

https://k8s-testgrid.appspot.com

@ethernetdan did some preliminary work on this.

**Comment by ethernetdan** [comment]
Testgrid data is populated in the bucket by the upstream [CI bootstrapper](https://github.com/kubernetes/test-infra/blob/master/jenkins/bootstrap.py).

It first publishes a timestamp in [`<Bucket Name>/<Job Name>/<Build Number>/started.json`](https://storage.googleapis.com/upstream-jenkins-logs/logs/ci-tectonic-e2e-etcd-serial/83/started.json) to denote the beginning of a job. This shows up in test grid as an incomplete job with a question mark.

After running the job it writes [`<Bucket Name>/<Job Name>/<Build Number>/finished.json`](https://storage.googleapis.com/upstream-jenkins-logs/logs/ci-tectonic-e2e-etcd-serial/83/finished.json) with information on whether the job failed and other metadata like version tested.

The runner also uploads artifacts like test results and logs generated by kubetest & ginkgo. These can be explored with Gubernator, [here](https://k8s-gubernator.appspot.com/build/upstream-jenkins-logs/logs/ci-tectonic-e2e-etcd-serial/83/)'s its page for the results linked above. Testgrid is configured to link to the Gubernator page for each result.

**Comment by ethernetdan** [comment]
Easiest way to achieve this is probably to recreate the test-infra setup reusing existing jobs and configure them for Tectonic. It may be desirable to have this configuration live in upstream to prevent accidental breaking upstream change. Due to the way testing assumptions are consumed getting to 100% passing will require a custom e2e runner anyway, [kops](https://github.com/kubernetes/test-infra/blob/master/kubetest/kops.go) has an example here.

**Comment by sym3tri** [comment]
moved https://coreosdev.atlassian.net/browse/INST-200
